'use client';
import {useEffect,useRef,useState} from 'react';
import {MapPin,Navigation,RotateCcw} from 'lucide-react';
import type {Course} from '@/lib/courses';
declare global {interface Window{L:any;}}
let leaflet:Promise<any>|null=null;
function loadLeaflet(){if(window.L)return Promise.resolve(window.L);if(!leaflet)leaflet=new Promise((resolve,reject)=>{const link=document.createElement('link');link.rel='stylesheet';link.href='/vendor/leaflet.css';document.head.appendChild(link);const s=document.createElement('script');s.src='/vendor/leaflet.js';s.onload=()=>resolve(window.L);s.onerror=()=>reject(Error('Map unavailable'));document.head.appendChild(s)});return leaflet;}
export default function AtlasMap({courses,selected,onSelect,onBounds,lang='en'}:{courses:Course[];selected?:string;onSelect:(id:string)=>void;onBounds?:(ids:string[])=>void;lang?:string}){
 const el=useRef<HTMLDivElement>(null),map=useRef<any>(null),layer=useRef<any>(null),latest=useRef(courses),select=useRef(onSelect),selectedRef=useRef(selected);const [error,setError]=useState(''),[ready,setReady]=useState(false),[tiles,setTiles]=useState(true),[moved,setMoved]=useState(false);latest.current=courses;select.current=onSelect;selectedRef.current=selected;
 const draw=()=>{if(!map.current||!window.L)return;const L=window.L,m=map.current;layer.current?.clearLayers();const groups:{point:any;items:Course[]}[]=[];for(const c of latest.current){const point=m.latLngToContainerPoint([c.lat,c.lng]);const found=groups.find(g=>g.point.distanceTo(point)<43);if(found)found.items.push(c);else groups.push({point,items:[c]});}for(const g of groups){const cs=g.items,count=cs.length,c=cs[0],active=cs.some(c=>c.id===selectedRef.current);const marker=L.marker([cs.reduce((a,c)=>a+c.lat,0)/count,cs.reduce((a,c)=>a+c.lng,0)/count],{icon:L.divIcon({className:'atlas-pin-wrap',html:`<span class="atlas-pin ${count>1?'cluster':''} ${active?'active':''}">${count>1?count:'<svg viewBox="0 0 24 24" width="18" height="18"><path d="M5 7h14M7 8l2 7h6l2-7M12 4v16M8 20h8" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>'}</span>`,iconSize:[34,40],iconAnchor:[17,35]}),title:count>1?`${count} courses`:c.name,keyboard:true});const tip=document.createElement('span');tip.textContent=count>1?`${count} ${lang==='is'?'vellir — stækka':'courses — zoom in'}`:c.name;marker.bindTooltip(tip,{direction:'top',offset:[0,-30]});marker.on('click',()=>{if(count>1)m.fitBounds(cs.map(c=>[c.lat,c.lng]),{padding:[70,70],maxZoom:13});else select.current(c.id)});marker.addTo(layer.current);}};
 useEffect(()=>{let disposed=false;loadLeaflet().then(async L=>{if(disposed||!el.current)return;const m=L.map(el.current,{zoomControl:false,scrollWheelZoom:false,minZoom:5,maxZoom:17,attributionControl:true}).setView([64.9,-18.7],6);map.current=m;L.control.zoom({position:'bottomright'}).addTo(m);const tile=L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> © <a href="https://carto.com/attributions">CARTO</a>',maxZoom:19});tile.on('tileerror',()=>setTiles(false));tile.addTo(m);try{const geo=await fetch('/iceland.geojson').then(r=>r.json());if(!disposed)L.geoJSON(geo,{style:{color:'#bccaba',weight:1,fillColor:'#edf0e8',fillOpacity:0.4},interactive:false}).addTo(m).bringToBack();}catch{}layer.current=L.layerGroup().addTo(m);m.fitBounds([[63.3,-24.7],[66.6,-13.2]],{padding:[25,25]});m.on('moveend',()=>{draw();setMoved(true)});draw();setReady(true);const resize=new ResizeObserver(()=>m.invalidateSize());resize.observe(el.current);(m as any)._resizeObserver=resize;}).catch(()=>setError(lang==='is'?'Kortið er ekki tiltækt. Notaðu vallalistann.':'The map could not load. All courses remain available in the list.'));return()=>{disposed=true;if(map.current){map.current._resizeObserver?.disconnect();map.current.remove();map.current=null;}setReady(false)};},[]);
 useEffect(()=>{if(ready)draw()},[courses,selected,ready]);
 return <div className="map-shell"><div ref={el} className="leaflet-map" aria-label={lang==='is'?'Gagnvirkt kort af Íslandi':'Interactive map of Iceland'} role="region"/>{!ready&&<div className="map-loading"><MapPin/><p>{error||(lang==='is'?'Hleð korti…':'Loading Iceland…')}</p></div>}<div className="map-top"><span className="map-title"><span className="map-dot"/>{lang==='is'?'ÍSLAND · VALLAKORT':'ICELAND · COURSE ATLAS'}</span><button className="map-reset icon-btn" aria-label="Reset map to Iceland" onClick={()=>map.current?.fitBounds([[63.3,-24.7],[66.6,-13.2]])}><RotateCcw size={17}/></button></div>{onBounds&&moved&&<button className="search-area" onClick={()=>{onBounds(courses.filter(c=>map.current?.getBounds().contains([c.lat,c.lng])).map(c=>c.id));setMoved(false)}}><Navigation size={14}/>{lang==='is'?'Leita á þessu svæði':'Search this area'}</button>}<div className="map-legend"><span className="legend-symbol"/>{lang==='is'?'Áætluð staðsetning · fyrsta teig þarf að staðfesta':'Approximate locations · first tees not yet verified'}</div>{!tiles&&<div className="map-fallback">{lang==='is'?'Grunnkort án nettengingar':'Offline outline · map tiles unavailable'}</div>}</div>
}
