'use client';
import {useState,useRef,useEffect} from 'react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Sparkles,Send,ArrowUpRight,MapPin,LoaderCircle} from 'lucide-react';
import type {Course,Lang} from '@/lib/courses';
export default function Caddie({open,onClose,course,lang}:{open:boolean;onClose:()=>void;course?:Course;lang:Lang}){const [question,setQuestion]=useState(''),[messages,setMessages]=useState<any[]>([]),[busy,setBusy]=useState(false);const end=useRef<HTMLDivElement>(null);const t=(en:string,is:string)=>lang==='is'?is:en;useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[messages,busy]);
 async function ask(q:string){if(!q.trim()||busy)return;const history=messages.slice(-6).map(m=>({role:m.role,content:m.text}));setMessages(m=>[...m,{role:'user',text:q}]);setQuestion('');setBusy(true);try{const r=await fetch('/api/caddie',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,courseId:course?.id,lang,history})});const data:any=await r.json();setMessages(m=>[...m,{role:'assistant',text:data.answer||data.error||t('The caddie is currently unavailable.','Aðstoðin er ekki tiltæk.'),courses:data.courses,mode:data.mode,error:!r.ok}]);}catch{setMessages(m=>[...m,{role:'assistant',text:t('Could not connect. Your question is above; please try again.','Tenging mistókst. Reyndu aftur.'),error:true}]);}finally{setBusy(false);}}
 return <Sheet open={open} onOpenChange={v=>!v&&onClose()}><SheetContent className="caddie-sheet" side="right"><SheetHeader><div className="caddie-mark"><Sparkles size={25}/></div><SheetTitle>{t('Ask the Iceland Caddie','Spyrðu Íslands-Caddie')}</SheetTitle><SheetDescription>{t('A little local knowledge. A better day outside.','Góðar upplýsingar fyrir daginn úti.')}</SheetDescription>{course&&<span className="context-chip"><MapPin size={13}/>{course.name}</span>}</SheetHeader><div className="chat-body" aria-live="polite">{messages.length===0&&<><p>{t('Where would you like to play? I can help you explore courses, compare your options, or plan the next stop.','Hvar viltu spila? Ég get hjálpað þér að finna velli, bera þá saman og skipuleggja ferð.')}</p><div className="suggestions">{[["Which beginner-friendly courses are near Reykjavík?","Hvaða vellir nálægt Reykjavík henta byrjendum?"],["Plan a three-day disc golf trip.","Skipuleggðu þriggja daga frisbígolfferð."],["Which saved courses have nine holes?","Hvaða vistuðu vellir eru með níu brautir?"]].map(([en,is])=><button onClick={()=>ask(t(en,is))} key={en}>{t(en,is)}<ArrowUpRight size={16}/></button>)}</div></>}{messages.map((m,i)=><div className={`chat-message ${m.role}`} key={i}><span className="eyebrow">{m.role==='user'?t('You','Þú'):t('Iceland Caddie','Íslands-Caddie')}</span><p>{m.text}</p>{m.mode&&<small>{m.mode}</small>}{m.courses?.map((c:Course)=><div className="chat-course" key={c.id}><a href={`/courses/${c.id}?lang=${lang}`}><strong>{c.name}</strong><span>{c.town} · {c.holes} {t('holes','brautir')}<ArrowUpRight size={14}/></span></a><a className="source-link" href={c.source} target="_blank" rel="noreferrer">{t('Source · checked','Heimild · skoðuð')} {c.checked}</a></div>)}</div>)}{busy&&<div className="loading-line"><LoaderCircle className="spin" size={17}/>{t('Checking the course database…','Skoða vallagögn…')}</div>}<div ref={end}/></div><form className="chat-form" onSubmit={e=>{e.preventDefault();ask(question)}}><label className="sr-only" htmlFor="caddie-input">{t('Your question','Spurning')}</label><input id="caddie-input" value={question} onChange={e=>setQuestion(e.target.value)} placeholder={t('Ask about courses, trips, or the game…','Spyrðu um velli, ferðir eða leikinn…')} maxLength={1800}/><button className="btn primary icon-btn" disabled={busy||!question.trim()} aria-label={t('Send question','Senda spurningu')}><Send size={18}/></button></form><p className="chat-footnote">{t('Course facts need sources. Conditions can change.','Vallaupplýsingar byggja á heimildum. Aðstæður geta breyst.')}</p></SheetContent></Sheet>
}
