'use client';
import {useEffect,useState,useMemo} from 'react';
import {Compass,Map,MapPin,Search,ArrowRight,ArrowUpRight,Bookmark,Navigation,SlidersHorizontal,Mountain,Route,BookOpen,CalendarDays,Sparkles,Menu,User,Check,Globe,Share2,X,Plus,Info,List,Flag,ShieldCheck,LoaderCircle} from 'lucide-react';
import {Toaster,toast} from 'sonner';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import AtlasMap from '@/components/atlas-map';
import CourseCard from '@/components/course-card';
import Caddie from '@/components/caddie';
import CourseProfile from '@/components/course-profile';
import {TripPlanner,Scorecard,SavedCourses} from '@/components/player-tools';
import {Learn,Events,Coverage,Clubs,Admin,Submission} from '@/components/resources';
import {Choice,Modal,Notice,External,api,shareUrl} from '@/components/primitives';
import {seedCourses,normalize,distanceKm,type Course,type Lang} from '@/lib/courses';
export type PlayerData={saves:{course_id:string;played:number}[];trips:any[];rounds:any[]};
export default function Experience({section,courseId}:{section:string;courseId?:string}){
 const [lang,setLang]=useState<Lang>('en'),[courses,setCourses]=useState(seedCourses),[user,setUser]=useState<any>(null),[loaded,setLoaded]=useState(false),[storage,setStorage]=useState(true),[me,setMe]=useState<PlayerData>({saves:[],trips:[],rounds:[]});
 const [q,setQ]=useState(''),[region,setRegion]=useState('all'),[holes,setHoles]=useState('all'),[difficulty,setDifficulty]=useState('all'),[terrain,setTerrain]=useState('all'),[parking,setParking]=useState(false),[sort,setSort]=useState('editorial'),[selected,setSelected]=useState<string>(),[compare,setCompare]=useState<string[]>([]),[area,setArea]=useState<string[]|null>(null),[location,setLocation]=useState<[number,number]|null>(null),[locating,setLocating]=useState(false),[locError,setLocError]=useState('');
 const [mapView,setMapView]=useState(false),[filterOpen,setFilterOpen]=useState(false),[compareOpen,setCompareOpen]=useState(false),[caddieOpen,setCaddieOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[submit,setSubmit]=useState<{kind:string;courseId?:string}|null>(null),[stops,setStops]=useState<string[]>([]);
 const t=(en:string,is:string)=>lang==='is'?is:en;const current=courses.find(c=>c.id===courseId);const href=(path:string)=>`${path}${path.includes('?')?'&':'?'}lang=${lang}`;
 async function refreshMe(){try{setMe(await api('/api/me'));}catch(e:any){toast.error(e.message)}}
 useEffect(()=>{const params=new URLSearchParams(window.location.search),l=params.get('lang')||(()=>{try{return localStorage.getItem('dgi-language')}catch{return null}})();if(l==='is')setLang('is');setQ(params.get('q')||'');setRegion(params.get('region')||'all');setHoles(params.get('holes')||'all');setDifficulty(params.get('difficulty')||'all');setTerrain(params.get('terrain')||'all');setParking(params.get('parking')==='yes');setSelected(params.get('selected')||undefined);if(params.has('area'))setArea((params.get('area')||'').split(','));setSort(params.get('sort')||'editorial');let draft:string[]=[];try{draft=JSON.parse(sessionStorage.getItem('dgi-trip-draft')||'[]')}catch{}setStops((params.get('stops')?.split(',')||draft).filter(id=>seedCourses.some(c=>c.id===id)));api('/api/catalog').then(d=>{setCourses(d.courses);setStorage(d.storage);setUser(d.user);if(d.user)refreshMe();}).catch(()=>setStorage(false)).finally(()=>setLoaded(true));if(params.get('nearby')==='true')locate();},[]);
 useEffect(()=>{document.documentElement.lang=lang;if(loaded)try{localStorage.setItem('dgi-language',lang)}catch{}},[lang,loaded]);
 useEffect(()=>{if(!loaded||!['atlas','explore'].includes(section))return;const p=new URLSearchParams();if(lang==='is')p.set('lang',lang);if(q)p.set('q',q);for(const [k,v] of Object.entries({region,holes,difficulty,terrain,sort}))if(v!=='all'&&v!=='editorial')p.set(k,v);if(parking)p.set('parking','yes');if(selected)p.set('selected',selected);if(area)p.set('area',area.join(','));history.replaceState(null,'',window.location.pathname+(p.size?'?'+p.toString():''));},[q,region,holes,difficulty,terrain,parking,sort,selected,area,lang,loaded]);
 useEffect(()=>{if(loaded)try{sessionStorage.setItem('dgi-trip-draft',JSON.stringify(stops))}catch{}},[stops,loaded]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const ctl=new AbortController();Promise.resolve(ctx.registerTool({name:'filter_course_atlas',title:'Filter the course atlas',description:'Update the visible atlas search and optional hole-count filter. Does not save records.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200},holes:{type:'integer',minimum:1,maximum:36}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(typeof input.query!=='string'||input.query.length>200||input.holes!==undefined&&(!Number.isInteger(input.holes)||input.holes<1||input.holes>36))throw Error('Invalid atlas filter');setQ(input.query);setHoles(input.holes?String(input.holes):'all');return {query:input.query,holes:input.holes||null};}},{signal:ctl.signal})).catch(()=>{});return()=>ctl.abort()},[]);
 function locate(){setLocating(true);setLocError('');if(!navigator.geolocation){setLocError(t('Location is unavailable. Search by town instead.','Staðsetning er ekki tiltæk. Leitaðu eftir bæ.'));setLocating(false);return;}navigator.geolocation.getCurrentPosition(p=>{setLocation([p.coords.latitude,p.coords.longitude]);setSort('distance');setLocating(false)},()=>{setLocError(t('Location permission was denied or unavailable. You can still search by town or region.','Staðsetning er óheimil eða ekki tiltæk. Leitaðu eftir bæ eða landshluta.'));setLocating(false)},{timeout:12000,maximumAge:60000});}
 async function save(c:Course,played?:boolean){if(!user){setAccountOpen(true);return;}const existing=me.saves.find(s=>s.course_id===c.id);try{await api('/api/me',{action:'save',id:c.id,saved:played!==undefined?true:!existing,played:played??!!existing?.played});await refreshMe();toast.success(played!==undefined?t('Played status updated','Spilunarstaða uppfærð'):existing?t('Course removed from saved','Völlur fjarlægður'):t('Course saved','Völlur vistaður'));}catch(e:any){toast.error(e.message)}}
 function addTrip(c:Course){setStops(s=>s.includes(c.id)?s:[...s,c.id]);toast.success(t(`${c.name} added to your trip draft`,`${c.name} bætt við ferðadrög`),{action:{label:t('View trip','Skoða ferð'),onClick:()=>window.location.assign(href('/trip-planner'))}})}
 function toggleCompare(id:string){if(compare.includes(id))setCompare(compare.filter(x=>x!==id));else if(compare.length<3)setCompare([...compare,id]);else toast(t('Compare up to three courses at a time.','Berðu saman allt að þrjá velli.'))}
 const filtered=useMemo(()=>{let result=courses.filter(c=>(!q||normalize([c.name,c.town,c.region,c.regionIs,c.id].join(' ')).includes(normalize(q)))&&(region==='all'||c.region===region)&&(holes==='all'||String(c.holes)===holes)&&(difficulty==='all'||c.difficulty===difficulty)&&(terrain==='all'||c.terrain===terrain)&&(!parking||c.parking===true)&&(!area||area.includes(c.id)));if(sort==='name')result.sort((a,b)=>a.name.localeCompare(b.name,'is'));if(sort==='distance'&&location)result.sort((a,b)=>distanceKm(location,[a.lat,a.lng])-distanceKm(location,[b.lat,b.lng]));if(sort==='editorial'){const order=['klambratun','hamrar','tjarnargardur'];result.sort((a,b)=>(order.includes(a.id)?order.indexOf(a.id):10)-(order.includes(b.id)?order.indexOf(b.id):10));}return result;},[courses,q,region,holes,difficulty,terrain,parking,sort,area,location]);
 const nav=[['Explore','Skoða','/','explore'],['Atlas','Vallakort','/atlas','atlas'],['Trip Planner','Ferðaáætlun','/trip-planner','trip-planner'],['Learn','Læra','/learn','learn'],['Events','Viðburðir','/events','events']];
 const card=(c:Course)=><CourseCard key={c.id} course={c} lang={lang} saved={me.saves.some(s=>s.course_id===c.id)} onSave={()=>save(c)} onTrip={()=>addTrip(c)} onCompare={()=>toggleCompare(c.id)} compared={compare.includes(c.id)} selected={selected===c.id} onSelect={()=>{setSelected(c.id);setMapView(true)}} distance={sort==='distance'&&location?distanceKm(location,[c.lat,c.lng]):undefined}/>;
 const filterCount=[region,holes,difficulty,terrain].filter(v=>v!=='all').length+(parking?1:0);
 function clearFilters(){setQ('');setRegion('all');setHoles('all');setDifficulty('all');setTerrain('all');setParking(false);setArea(null)}
 return <><Toaster richColors position="bottom-center"/><a className="skip-link" href="#main">{t('Skip to content','Fara í efni')}</a><header className="site-header"><div className="header-inner"><a className="brand" href={href('/')}><img src="/favicon.svg" width="36" height="36" alt=""/><span>DISC GOLF <b>ICELAND</b></span></a><nav className="desktop-nav" aria-label={t('Main navigation','Aðalvalmynd')}>{nav.map(([en,is,path,id])=><a key={id} href={href(path)} className={section===id?'nav-active':''}>{t(en,is)}</a>)}</nav><div className="header-actions"><a className={`saved-nav ${section==='saved'?'nav-active':''}`} href={href('/saved')}><Bookmark size={17}/><span>{t('Saved','Vistað')}</span>{me.saves.length>0&&<b>{me.saves.length}</b>}</a><div className="language-switch" aria-label="Language / Tungumál"><button className={lang==='en'?'active':''} onClick={()=>setLang('en')} aria-pressed={lang==='en'}>EN</button><span>/</span><button className={lang==='is'?'active':''} onClick={()=>setLang('is')} aria-pressed={lang==='is'}>IS</button></div><button className="icon-btn account-btn" onClick={()=>setAccountOpen(true)} aria-label={t('Your account','Aðgangurinn þinn')}><User size={18}/></button><button className="icon-btn mobile-menu" aria-label="Menu" onClick={()=>setMenuOpen(true)}><Menu/></button></div></div></header>
 <main id="main">{!storage&&loaded&&<div className="service-notice">{t('The source-checked directory is available. Saving and recent updates may be temporarily unavailable.','Vallaskráin er tiltæk. Vistun og nýjustu uppfærslur gætu verið óvirkar tímabundið.')}</div>}
 {['explore','atlas'].includes(section)&&<><section className={section==='explore'?'explore-intro':'atlas-intro'}>{section==='explore'&&<img src="/images/iceland.jpg" alt="Mountains and green valley in Landmannalaugar, Iceland" className="intro-photo" fetchPriority="high"/>}<div className="container intro-content"><div><span className="eyebrow">{t('GOOD ROUNDS. GREAT PLACES.','GÓÐIR HRINGIR. FALLEGT LAND.')}</span><h1>{section==='explore'?t('Find your next fairway.','Finndu næsta völl.'):t('The Iceland course atlas.','Frisbígolfvellir á Íslandi.')}</h1><p>{t('Discover a different side of Iceland. One course at a time.','Uppgötvaðu nýja hlið á Íslandi. Einn völl í einu.')}</p></div>{section==='explore'?<span className="hero-location"><MapPin size={14}/>Landmannalaugar, Iceland<br/><small>{t('Landscape photograph · Amy Hanley','Landslagsmynd · Amy Hanley')}</small></span>:<button className="btn subtle" onClick={async()=>{const ok=await shareUrl(window.location.href);ok?toast.success(t('Atlas link copied','Tengill afritaður')):toast.error(t('Copy the address from your browser.','Afritaðu slóð úr vafranum.'))}}><Share2 size={16}/>{t('Share this view','Deila þessari sýn')}</button>}</div></section>
 <div className="container atlas-workspace"><div className="search-row"><div className="search-field"><Search size={20}/><label className="sr-only" htmlFor="course-search">{t('Search courses, towns, or regions','Leita að völlum, bæjum eða landshlutum')}</label><input id="course-search" value={q} onChange={e=>setQ(e.target.value)} placeholder={t('Search a course, town, or region…','Leita að velli, bæ eða landshluta…')}/>{q&&<button className="icon-btn" aria-label="Clear search" onClick={()=>setQ('')}><X size={16}/></button>}</div><button className="btn primary nearby" onClick={locate} disabled={locating}>{locating?<LoaderCircle size={17} className="spin"/>:<Navigation size={17}/>}<span>{t('Find courses near me','Finna velli nálægt mér')}</span></button>{section==='explore'&&<a className="btn atlas-link" href={href('/atlas')}><Map size={18}/>{t('Explore the atlas','Skoða vallakortið')}<ArrowUpRight size={15}/></a>}</div>{locError&&<Notice>{locError}</Notice>}
 <div className="filter-row"><div className="main-filters"><Choice label={t('Region','Landshluti')} value={region} onChange={v=>{setRegion(v);setArea(null)}} options={[{value:'all',label:t('All regions','Allir landshlutar')},...Array.from(new Set(courses.map(c=>c.region))).map(r=>({value:r,label:lang==='is'?courses.find(c=>c.region===r)!.regionIs:r}))]}/><Choice label={t('Hole count','Fjöldi brauta')} value={holes} onChange={setHoles} options={[{value:'all',label:t('Any hole count','Allar brautir')},...[6,9,14,18].map(n=>({value:String(n),label:`${n} ${t('holes','brautir')}`}))]}/><button className={`btn filter-btn ${filterCount?'has-filters':''}`} onClick={()=>setFilterOpen(true)}><SlidersHorizontal size={16}/>{t('More filters','Fleiri síur')}{filterCount>0&&<b>{filterCount}</b>}</button>{(filterCount>0||area)&&<button className="small-link" onClick={clearFilters}>{t('Reset','Hreinsa')}<X size={13}/></button>}</div><p className="source-note"><ShieldCheck size={15}/>{t('Real courses. Referenced sources.','Raunverulegir vellir. Skráðar heimildir.')}</p></div>
 <div className="results-top"><p><strong>{filtered.length}</strong> {t('courses to explore','vellir til að skoða')}<span className="muted"> · {t('Growing coverage','Vaxandi skrá')}</span></p><div className="results-tools"><Choice label={t('Sort courses','Raða völlum')} value={sort} onChange={setSort} options={[{value:'editorial',label:t('Featured first','Valdir vellir fyrst')},{value:'name',label:t('Course name','Nafn vallar')},{value:'distance',label:t('Distance','Fjarlægð'),disabled:!location}]}/><div className="mobile-toggle"><button className={!mapView?'active':''} onClick={()=>setMapView(false)} aria-pressed={!mapView}><List size={15}/>{t('List','Listi')}</button><button className={mapView?'active':''} onClick={()=>setMapView(true)} aria-pressed={mapView}><Map size={15}/>{t('Map','Kort')}</button></div></div></div>
 <div className={`atlas-split ${mapView?'show-map':''}`}><div className="course-list">{filtered.length?filtered.map(card):<div className="empty-state"><Search size={34}/><h3>{t('No courses match just yet.','Engir vellir passa við leitina.')}</h3><p>{t('Try another town or remove a filter. Unknown attributes are excluded from specific filters.','Prófaðu annan bæ eða fjarlægðu síu.')}</p><button className="btn primary" onClick={clearFilters}>{t('Clear filters','Hreinsa síur')}</button></div>}</div><div className="map-column"><AtlasMap courses={filtered} selected={selected} onSelect={setSelected} onBounds={setArea} lang={lang}/>{selected&&courses.find(c=>c.id===selected)&&<div className="map-preview"><div><small>{t('SELECTED COURSE','VALINN VÖLLUR')}</small><h3>{courses.find(c=>c.id===selected)!.name}</h3><p>{courses.find(c=>c.id===selected)!.town} · {courses.find(c=>c.id===selected)!.holes} {t('holes','brautir')}</p></div><a className="btn primary" href={href('/courses/'+selected)}>{t('View course','Skoða völl')}<ArrowUpRight size={15}/></a><button className="icon-btn" onClick={()=>setSelected(undefined)} aria-label="Close course preview"><X size={17}/></button></div>}</div></div>
 <div className="atlas-caption"><span>{t('Featured first: a geographic mix of source-checked listings, not a ranking.','Valdir vellir: landfræðileg dreifing staðfestra skráninga, ekki einkunnagjöf.')}</span><a href={href('/coverage')}>{t('Our verification process','Hvernig við staðfestum gögn')}<ArrowUpRight size={14}/></a></div>
 {section==='explore'&&<><section className="caddie-banner"><div className="banner-icon"><Sparkles size={27}/></div><div><span className="eyebrow">{t('A LITTLE GUIDANCE GOES A LONG WAY','GÓÐ LEIÐSÖGN SKIPTIR MÁLI')}</span><h2>{t('Meet your Iceland Caddie.','Kynntu þér Íslands-Caddie.')}</h2><p>{t('Find your kind of course. Make a plan. Ask away.','Finndu völl við þitt hæfi. Skipuleggðu ferð. Spurðu okkur.')}</p></div><button className="btn primary" onClick={()=>setCaddieOpen(true)}>{t('Ask the caddie','Spyrja Caddie')}<ArrowUpRight size={16}/></button></section><div className="resource-grid"><a href={href('/learn')}><BookOpen/><span className="eyebrow">{t('NEW TO THE GAME?','NÝR Í ÍÞRÓTTINNI?')}</span><h3>{t('Your first round starts here.','Fyrsti hringurinn byrjar hér.')}</h3><p>{t('The basics, the etiquette, and what to bring.','Grunnatriði, kurteisi og útbúnaður.')}</p><span className="text-link">{t('Get to know disc golf','Kynntu þér frisbígolf')}<ArrowRight size={16}/></span></a><a href={href('/trip-planner')}><Route/><span className="eyebrow">{t('TAKE THE SCENIC ROUTE','NÝTT ÆVINTÝRI')}</span><h3>{t('A few courses. One good trip.','Nokkrir vellir. Ein góð ferð.')}</h3><p>{t('Bring your next Iceland adventure together.','Settu saman næsta ferðalag um Ísland.')}</p><span className="text-link">{t('Build your itinerary','Skipuleggðu ferðina')}<ArrowRight size={16}/></span></a><a href={href('/events')}><CalendarDays/><span className="eyebrow">{t('ON THE CALENDAR','Á DAGSKRÁ')}</span><h3>{t('Find your next gathering.','Finndu næsta viðburð.')}</h3><p>{t('Only events with a checked official source.','Aðeins viðburðir með staðfestum heimildum.')}</p><span className="text-link">{t('See verified events','Skoða staðfesta viðburði')}<ArrowRight size={16}/></span></a></div></>}
 </div></>}
 {section==='course'&&current&&<CourseProfile course={current} lang={lang} saved={me.saves.some(s=>s.course_id===current.id)} onSave={()=>save(current)} onTrip={()=>addTrip(current)} onAsk={()=>setCaddieOpen(true)} onSubmit={kind=>setSubmit({kind,courseId:current.id})}/>}
 {section==='trip-planner'&&<TripPlanner courses={courses} stops={stops} setStops={setStops} lang={lang} user={user} onSignIn={()=>setAccountOpen(true)} onSaved={refreshMe}/>}
 {section==='scorecard'&&<Scorecard courses={courses} lang={lang} user={user} onSignIn={()=>setAccountOpen(true)} onSaved={refreshMe}/>}
 {section==='saved'&&<SavedCourses courses={courses} me={me} lang={lang} user={user} onSignIn={()=>setAccountOpen(true)} renderCard={card} onPlayed={save} onRefresh={refreshMe}/>}
 {section==='learn'&&<Learn lang={lang}/>}{section==='events'&&<Events lang={lang} onSubmit={()=>setSubmit({kind:'event'})}/>}{section==='coverage'&&<Coverage lang={lang} courses={courses} onSubmit={()=>setSubmit({kind:'missing'})}/>}{section==='clubs'&&<Clubs lang={lang}/>}{section==='admin'&&<Admin lang={lang} user={user} loaded={loaded}/>}
 </main>
 <footer className="site-footer container"><div className="footer-brand"><Mountain size={22}/><b>DISC GOLF ICELAND</b><span>{t('A good day starts outside.','Góður dagur byrjar úti.')}</span></div><div><a href={href('/coverage')}>{t('Sources & coverage','Heimildir og skráning')}</a><a href={href('/clubs')}>{t('Clubs','Félög')}</a><button onClick={()=>setSubmit({kind:'missing'})}>{t('Submit a course','Senda inn völl')}</button><a href={href('/admin')}>{t('Administration','Umsjón')}</a></div><small>© {new Date().getFullYear()} Disc Golf Iceland · {t('Independent course guide','Óháður vallavísir')}</small></footer>
 <button className="caddie-floating" onClick={()=>setCaddieOpen(true)}><Sparkles size={19}/><span>{t('Ask the Iceland Caddie','Spyrðu Íslands-Caddie')}</span></button>
 {compare.length>0&&<div className="compare-bar"><span>{compare.length}/3 {t('courses selected','vellir valdir')}</span><button className="btn primary" onClick={()=>setCompareOpen(true)}>{t('Compare courses','Bera saman velli')}<ArrowRight size={15}/></button><button className="icon-btn" onClick={()=>setCompare([])} aria-label="Clear comparison"><X size={16}/></button></div>}
 <Modal open={filterOpen} onClose={()=>setFilterOpen(false)} title={t('Find your kind of course','Finndu völl við þitt hæfi')} description={t('Filters use documented facts. Courses with unknown values will be excluded.','Síur byggja á skráðum upplýsingum. Óþekkt gildi eru undanskilin.')}><div className="form-stack"><label>{t('Difficulty','Erfiðleiki')}<Choice label="Difficulty" value={difficulty} onChange={setDifficulty} options={[{value:'all',label:t('Any difficulty','Öll erfiðleikastig')},{value:'Beginner friendly',label:t('Beginner friendly','Fyrir byrjendur')},{value:'Challenging',label:t('Challenging','Krefjandi')}]}/></label><label>{t('Terrain','Landslag')}<Choice label="Terrain" value={terrain} onChange={setTerrain} options={[{value:'all',label:t('Any terrain','Allt landslag')},{value:'Park',label:t('Park','Garður')},{value:'Woodland',label:t('Woodland','Skógur')},{value:'Valley',label:t('Valley','Dalur')}]}/></label><label className="checkbox-label"><Checkbox checked={parking} onCheckedChange={v=>setParking(v===true)}/>{t('Documented parking','Skráð bílastæði')}</label><Notice>{t('Fees, access, accessibility, and community ratings need more verification before they can be used as filters.','Gjöld, aðgengi og einkunnir þurfa frekari staðfestingu áður en þau verða síur.')}</Notice><button className="btn primary" onClick={()=>setFilterOpen(false)}>{t(`Show ${filtered.length} courses`,`Sýna ${filtered.length} velli`)}</button></div></Modal>
 <Modal open={compareOpen} onClose={()=>setCompareOpen(false)} title={t('Compare your next round','Berðu saman næsta hring')} description={t('Side by side, using documented attributes.','Samanburður byggður á skráðum upplýsingum.')} wide><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>{t('Attribute','Atriði')}</TableHead>{compare.map(id=><TableHead key={id}><a href={href('/courses/'+id)}>{courses.find(c=>c.id===id)?.name}</a></TableHead>)}</TableRow></TableHeader><TableBody>{[['town',t('Town','Bær')],['holes',t('Holes','Brautir')],['terrain',t('Terrain','Landslag')],['difficulty',t('Difficulty','Erfiðleiki')],['fees',t('Fees','Gjöld')],['access',t('Access','Aðgengi')],['checked',t('Last checked','Síðast skoðað')]].map(([key,label])=><TableRow key={key}><TableCell>{label}</TableCell>{compare.map(id=><TableCell key={id}>{(courses.find(c=>c.id===id) as any)?.[key]||t('Not yet verified','Ekki enn staðfest')}</TableCell>)}</TableRow>)}</TableBody></Table></div></Modal>
 <Modal open={accountOpen} onClose={()=>setAccountOpen(false)} title={user?t('Your Iceland adventures','Ævintýrin þín á Íslandi'):t('Keep your next adventure close','Geymdu næsta ævintýri')} description={user?t('Your saved courses, trips, and round history stay private.','Vistaðir vellir, ferðir og hringir eru einkamál.'):t('Browse freely. Sign in to save courses, trips, rounds, or submit community content.','Skoðaðu án innskráningar. Skráðu þig inn til að vista og senda inn efni.')}><div className="form-stack">{user?<><p>{t('Signed in as','Innskráður sem')} <strong>{user.name}</strong></p><a className="btn primary" href={href('/saved')}>{t('Open saved courses & history','Opna vistaða velli og sögu')}<ArrowRight size={16}/></a><a className="text-link" href="/signout-with-chatgpt?return_to=/" target="_top">{t('Sign out','Skrá út')}</a></>:<a className="btn primary" href={`/signin-with-chatgpt?return_to=${encodeURIComponent(typeof window!=='undefined'?window.location.pathname:'/saved')}`} target="_top">{t('Sign in with ChatGPT','Skrá inn með ChatGPT')}<ArrowRight size={16}/></a>}<Notice>{t('Location is requested only when you choose “near me”. Your saved lists and round history are never public. Submissions are published only after moderation.','Staðsetning er aðeins notuð þegar þú velur nálæga velli. Vistaðir listar og spilunarsaga eru ekki opinber. Innsent efni fer í yfirferð.')}</Notice></div></Modal>
 <Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetContent><SheetHeader><SheetTitle>Disc Golf Iceland</SheetTitle><SheetDescription>{t('Explore Iceland, one course at a time.','Skoðaðu Ísland, einn völl í einu.')}</SheetDescription></SheetHeader><nav className="mobile-nav">{nav.map(([en,is,path,id])=><a key={id} href={href(path)}>{t(en,is)}<ArrowUpRight size={18}/></a>)}<a href={href('/saved')}>{t('Saved courses','Vistaðir vellir')}</a></nav></SheetContent></Sheet>
 <Caddie open={caddieOpen} onClose={()=>setCaddieOpen(false)} course={current} lang={lang}/><Submission data={submit} onClose={()=>setSubmit(null)} lang={lang} user={user} onSignIn={()=>{setSubmit(null);setAccountOpen(true)}}/>
 </>;
}
