import {z} from 'zod';
import {db,requireUser,catalog,json,error,sameOrigin,body,ApiError} from '@/lib/server';
const score=z.object({courseId:z.string().min(1),layout:z.string().max(80),pars:z.array(z.number().int().min(1).max(10)).min(1).max(36),players:z.array(z.object({name:z.string().trim().min(1).max(50),scores:z.array(z.number().int().min(1).max(30)).min(1).max(36)})).min(1).max(6)});
export async function GET(){try{const u=await requireUser(),d=db();const [s,t,r]=await Promise.all([d.prepare('SELECT course_id,played FROM saves WHERE user_id=?').bind(u.userId).all(),d.prepare('SELECT id,name,data,updated FROM trips WHERE user_id=? ORDER BY updated DESC').bind(u.userId).all(),d.prepare('SELECT id,course_id,data,created FROM rounds WHERE user_id=? ORDER BY created DESC').bind(u.userId).all()]);return json({saves:s.results,trips:t.results.map((x:any)=>({...x,data:JSON.parse(x.data)})),rounds:r.results.map((x:any)=>({...x,data:JSON.parse(x.data)}))});}catch(e){return error(e);}}
export async function POST(req:Request){try{sameOrigin(req);const u=await requireUser(),b=await body(req),d=db(),now=new Date().toISOString();
 if(b.action==='save'){const v=z.object({id:z.string(),saved:z.boolean(),played:z.boolean().optional()}).parse(b);if(!(await catalog()).some(c=>c.id===v.id))throw new ApiError('Course not found.',404);if(v.saved)await d.prepare('INSERT INTO saves (user_id,course_id,played) VALUES (?,?,?) ON CONFLICT(user_id,course_id) DO UPDATE SET played=excluded.played').bind(u.userId,v.id,v.played?1:0).run();else await d.prepare('DELETE FROM saves WHERE user_id=? AND course_id=?').bind(u.userId,v.id).run();return json({ok:true});}
 if(b.action==='trip'){const v=z.object({name:z.string().trim().min(1).max(80),stops:z.array(z.string()).min(1).max(20),start:z.string().max(100)}).parse(b);const cs=await catalog();if(v.stops.some(id=>!cs.some(c=>c.id===id)))throw new ApiError('An itinerary stop was not found.');const id=crypto.randomUUID();await d.prepare('INSERT INTO trips (id,user_id,name,data,updated) VALUES (?,?,?,?,?)').bind(id,u.userId,v.name,JSON.stringify({stops:v.stops,start:v.start}),now).run();return json({ok:true,id});}
 if(b.action==='round'){const v=score.parse(b);const c=(await catalog()).find(c=>c.id===v.courseId);if(!c)throw new ApiError('Course not found.',404);if(v.players.some(p=>p.scores.length!==v.pars.length))throw new ApiError('Every player must have a score for each hole.');const official=c.layouts.find(l=>l.name===v.layout&&l.pars);if(official&&JSON.stringify(v.pars)!==JSON.stringify(official.pars))throw new ApiError('The selected layout has changed. Reload its verified pars.');if(!official&&!v.layout.startsWith('Manual'))throw new ApiError('Use a manual layout when official pars are unavailable.');const result={...v,totals:v.players.map(p=>({name:p.name,throws:p.scores.reduce((a,b)=>a+b,0),relative:p.scores.reduce((a,b)=>a+b,0)-v.pars.reduce((a,b)=>a+b,0)}))};const id=crypto.randomUUID();await d.batch([d.prepare('INSERT INTO rounds (id,user_id,course_id,data,created) VALUES (?,?,?,?,?)').bind(id,u.userId,v.courseId,JSON.stringify(result),now),d.prepare('INSERT INTO saves (user_id,course_id,played) VALUES (?,?,1) ON CONFLICT(user_id,course_id) DO UPDATE SET played=1').bind(u.userId,v.courseId)]);return json({ok:true,id,result});}
 if(b.action==='deleteTrip'){const id=z.string().uuid().parse(b.id);await d.prepare('DELETE FROM trips WHERE id=? AND user_id=?').bind(id,u.userId).run();return json({ok:true});}
 throw new ApiError('Unknown action.');}catch(e){return error(e);}}
